### ISSUE TITLE
router history support and push new url to address bar?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#13]
At the moment router handle the request (remote template) or use the callback to handle it manually.
Both works fine, but is history support planned? To support browser back / forward and push the new URL to the address bar?

**Comment by anywhichway** [comment]
@pwFoo History support is planned. Considering doing it in the context of a static route table, e.g.

```
tlx.routes = {
  "/route1/somefile.html": {
     title: "some title",
     target: "some url" || a function // if function returns falsy, then additional routes will also be tested
  },
  "route2/somefile.html": {
     title: "some title",
     target: "some url" || a function
  }
}
```

**Comment by anywhichway** [comment]
@pwFoo Added history and nav bar update with v1.0.31. Did not add a static route table. See the updated `examples/route.html`. Consider this a beta. Very open to feedback.

**Comment by pwFoo** [comment]
First test with example looks good (address bar, back button works fine). 👍
