### ISSUE TITLE
Bind value by attribute instead of variable inside of html element?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#14]
At the moment we need to put a variable / placeholder inside of  the element, right?
```
<div class="fields" id="field1">${firstname}</div>
```

Would it possible to add attribute based binding like that?
```
<div class="fields" id="field1" t-value="${firstname}"></div>
```
It should replace the innerhtml / element content entirely. That would work with server side filled values, but it's possible to update / replace client side by "t-value" attribute?

**Comment by pwFoo** [comment]
Looks similar to [t-bind custom directive](https://github.com/anywhichway/tlx/blob/master/examples/t_bind_custom_directive.html)?

But would be nice to have it in core I think? Instead of use `${var}` inside of html element just use `t-bind` to bind / update element innerhtml?

**Comment by pwFoo** [comment]
@anywhichway 
If you won't add it to core would be nice if you could help me with a working custom directive because I haven't understand yet how to do it.

**Comment by anywhichway** [comment]
@pwFoo I can add something like this. Would prefer t-content or t-html or t-text since `value` is specific attribute on input elements. Pretty slammed this week, but if i get insomnia one night ...

**Comment by pwFoo** [comment]
Hi @anywhichway 
If you implement it just name it as you want. Would be great to have that feature.  👍 

I started coding after some time again and try to build a template module for my preferred cms / cmf based on tlx.

**Comment by anywhichway** [comment]
@pwFoo `t-content` has been added.
