### ISSUE TITLE
Handle nodelists is broken?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#16]
Hi @anywhichway,

looks like nodelist handling is broken?
Please test with example issue6.html

Replaced just the script line to include the latest release 1.0.40.

console output:
![image](https://user-images.githubusercontent.com/333408/57966683-a772a400-7955-11e9-90a6-e0cfbc48fa8c.png)

**Comment by anywhichway** [comment]
@pwFoo Thanks for finding the bug.
