### ISSUE TITLE
Use with Hyperapp?

### ISSUE THREAD

**Issue by jorgebucaran** [anywhichway/tlx#2]
Hi! I noticed this tiny awesome new library and I was wondering if it could be used with [Hyperapp](https://github.com/hyperapp/hyperapp).

Cheers!

**Comment by anywhichway** [comment]
@JorgeBucaran You probably could use it with Hyperapp, although you might also want to look at Hyperx.

**Comment by jorgebucaran** [comment]
@anywhichway Thanks! I was aware of hyperx, but just curious if tlx could have been used instead. Cheers.

**Comment by anywhichway** [comment]
The newest version of Tlx can effectively be used as a replacement for Hyperapp.

**Comment by jorgebucaran** [comment]
@anywhichway You mean as a replacement for hyperx/JSX to use with Hyperapp?

**Comment by anywhichway** [comment]
@jorgebucaran No, it can be used as a complete replacement for Hyperapp. It also supports linkState like Preact, templates like Riot, and directives like Vue.

**Comment by jorgebucaran** [comment]
@anywhichway Ah, gotcha!

Welcome to the club! 👋😄

**Comment by jorgebucaran** [comment]
Completely forgot about this issue. Seems good to close here. 👋
