### ISSUE TITLE
html comment breaks tlx?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#21]
If a Add a comment to html code it breaks tlx?
I added `<!-- moved to foreach because forvalues is NOT working as should? -->` and geht that error message:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at slice (<anonymous>)
    at E (tlx.min.js:1)
    at C (tlx.min.js:1)
    at tlx.min.js:1
    at Array.forEach (<anonymous>)
    at C (tlx.min.js:1)
    at Object.T [as view] (tlx.min.js:1)
    at index.html:49
```

And if I remove the comment again all works without error.

**Comment by anywhichway** [comment]
Since tx does not use a full parser comments are not supported.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pwFoo** [comment]
Ok, you should add it to the readme file. If tlx.js is used all html comments need to be removed from source Code to not break the app.
