### ISSUE TITLE
Working router() example?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#4]
Tried to use tlx.router() but without success. 
No JS / TLX action logged in console with tests like that (and some others...).
```
        tlx.router({
            '/test/1': args => {
                console.log('test...')
                alert ("TEST");
            }
        })
```

```
        tlx.handlers({click: tlx.router({"/test/:id": args => {
	        const view = this.target.view; 
                alert(view);
	        this.stopRoute(); 
	        view.parentNode.replaceChild(MyComponent(args),view);
	    }})});
```

**Comment by pwFoo** [comment]
Hi @anywhichway 
thanks for the example
https://github.com/anywhichway/tlx/blob/master/examples/router.html

But it doesn't work for me with Chrome, Firefox, Edge or Opera?

Result is an 404 error. Nothing logged in JS console, just the 404 and the navigated info. No `console.log()` or `alert`?
```
GET http://127.0.0.1/test/1 404 (Not Found)
Navigated to http://127.0.0.1/test/1
```

**Comment by pwFoo** [comment]
Tested a simple `tlx.handlers()` example which works fine
```
const test = tlx.handlers({click: (event) => { event.preventDefault(); console.log(event); alert("test") }});
tlx.view(document.getElementById("routed"),{controller:test});
```

Here the router example which not works.
```
const router =  tlx.router({
  '/tlx/:id': args => {
    console.log(args);
    alert("TEST");
}});
const handlers = tlx.handlers({click:router});
tlx.view(document.getElementById("routed"),{controller:handlers});
```

The `tlx.view()` should be fine. So problem could be `tlx.router()` or the handlers definition?

Working `tlx.handlers()` example without router.
```
const test = tlx.handlers({click: (event) => { event.preventDefault(); alert("test") }});
tlx.view(document.getElementById("routed"),{controller:test});
```

**Comment by anywhichway** [comment]
@pwFoo Added router example in v1.0.27:

```
<html lang="en">
<head>
<script src="https://unpkg.com/tlx/browser/tlx.min.js"></script>
<script src="../index.js"></script>
</head>
<body>
<a id="routed" href="/test/1">Click Me</div>
<script>
const router =  tlx.router({
  '/test/:id': args => {
    console.log(args);
    alert("TEST");
  }}),
  handlers = tlx.handlers({click:router});
tlx.view(document.getElementById("routed"),{controller:handlers});
</script>
</body>
</html>
```

**Comment by anywhichway** [comment]
@pwFoo You may have a caching problem. Try either clearing your cache or removing the unpkg reference and running the example from the tlx examples directory to ensure the most recent tlx is being used. The example has been update in v1.0.28 with comments to make it clear what is going on with library loading.

**Comment by pwFoo** [comment]
Mh, tested again with tlx.js instead of tlx.min.js from unpkg and also copied the latest index.js with same result. Sure it works fine...? Don't know what could be wrong. 1:1 copy of router.html and index.js files...

**Comment by anywhichway** [comment]
@pwFoo Think I just found the issue. It was a bug. The code for loading over file: was different than over http(s):. Were you loading from a server? (Also, check out new feature ... loading a url as a template. See example remote_template.html). See v1.0.29.

**Comment by pwFoo** [comment]
I using a local xampp for testing.
Yes, you fixed it! Works fine!

**Comment by pwFoo** [comment]
@anywhichway 
Remote template example ... That's magic. 🥇 

![image](https://user-images.githubusercontent.com/333408/50452518-c470f100-093a-11e9-9d90-795b09590e48.png)

I found the fetch in the source code. 
Really a nice feature I'll like instead of embedded templates in script tags or js code! Thanks 👍

**Comment by anywhichway** [comment]
@pwFoo You are welcome!
