### ISSUE TITLE
Data binding with input field

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#5]
I tried a data binding example and it works fine if I leave the input field, but shouldn't it update as I type?

If I change the variable value in model it also changes the textfield, but how to change the input field value too?

```
<!DOCTYPE html>
<html lang="de">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Titel der Seite | Name der Website</title>
    <script src="https://unpkg.com/tlx/browser/tlx.min.js"></script>
  </head>
  <body>
    <div id="field1">Hello ${firstname}</div>
    <div id="field2">Hello ${firstname}</div>
    <div>First Name: <input id="firstName" name="firstname" value="${firstname}" protect></div>

    <script type="text/javascript">
        const model = tlx.reactor();
        tlx.view(document.getElementById("field1"),{model});
        tlx.view(document.getElementById("field2"),{model});
        tlx.view(document.getElementById("firstName"),{model,linkModel:true})
    </script>
  </body>
</html>
```

Reproduce:
1. Type to input field
1. Leave input field to get the bind fields updated
1. change variable from web developer console to update the bind fields, but input field is unchanged by console value change?

I don't know how other data binding solutions do that (or not??).

**Comment by anywhichway** [comment]
At the moment reactive updates are lazy, i.e. wait for onchange. Will look at adding an option to make more aggressive, i.e. as typing.

Will check into updating from console. Are you sure you are updating the reactive proxy and not the underlying object?

Get Outlook for Android<https://aka.ms/ghei36>



From: pwFoo
Sent: Saturday, December 22, 12:31
Subject: [anywhichway/tlx] Data binding with input field (#5)
To: anywhichway/tlx
Cc: Subscribed


I tried a data binding example and it works fine if I leave the input field, but shouldn't it update as I type?
If I change the variable value in model it also changes the textfield, but how to change the input field value too?
<!DOCTYPE html> <html lang="de"> <head> <meta charset="utf-8" /> <meta name="viewport" content="width=device-width, initial-scale=1.0" /> <title>Titel der Seite | Name der Website</title> <script src="https://unpkg.com/tlx/browser/tlx.min.js"></script> </head> <body> <div> <a href="/tlx/test/1">ID1</a> | <a href="./test/2">ID2</a> </div> <div id="field1">Hello ${firstname}</div> <div id="field2">Hello ${firstname}</div> <div>First Name: <input id="firstName" name="firstname" value="${firstname}" protect></div> <script type="text/javascript"> const model = tlx.reactor(); tlx.view(document.getElementById("field1"),{model}); tlx.view(document.getElementById("field2"),{model}); tlx.view(document.getElementById("firstName"),{model,linkModel:true}) </script> </body> </html>
Reproduce:
Type to input field Leave input field to get the bind fields updated change variable from web developer console to update the bind fields, but input field is unchanged by console value change?
I don't know how other data binding solutions do that (or not??).

**Comment by pwFoo** [comment]
> Are you sure you are updating the reactive proxy and not the underlying object?
How can I update the reactive proxy? I changed the variable / object (like `model.firstname`) I bind to the element with `tlx.view()`.

**Comment by anywhichway** [comment]
@pwFoo Fixed in v1.0.24. Unit test and example added.

**Comment by pwFoo** [comment]
@anywhichway Works fine! Great! Thanks! 👍

**Comment by anywhichway** [comment]
@pwFoo In the next push, you will be able to aggressive reactive input:

`boolean||string linkModel` - If truthy, then the `model` is automatically updated with values from form fields having a `name` attribute by using the `name` attribute value as the key on the model. If the value of `linkModel` is a string, then that event is used to trigger updates, typically this would be "change" or "input". Use "change" for triggering when a field loses
focus, use "input" to react to every keystroke. If the value is truthy but not a string, "change" will be used.

**Comment by pwFoo** [comment]
Works fine! Great.
Thanks for your work and tlx framework! I love it! 👍

**Comment by anywhichway** [comment]
You are welcome.

Did you consider React or Vue for what you are working on? If so, we would
be interested in why you like TLX better.

**Comment by pwFoo** [comment]
At the moment I'm new with frameworks like vuejs, react, ...

I searched for an easy and small framework with the features (templating with if, loops and reactive data / two way data bindings) I tested with a project idea (simple project, stopped after some tests. I'm not a web developer...).

For my needs tinybind (rivets.js) was a nice solution with just the needed features. Routers are missing, so I have to use a standalone router solution (I think it was navigo).

The way was just html templates and async loaded json data rendered by data binding / reactive data.
Haven't worked with js embedded templates / html code and like to separate it...

I like the small code base, syntax and learning with each new example added to the repo how to use all the tlx features.
And I like projects which try to keep it simple and small and with all needed features I would prefer a project like tlx over react / vue :)

**Comment by pwFoo** [comment]
Because of size I can try to understand the code. That's why I would like to see even more comments about what the code snippet / block is doing, because for me it's easier to understand with additional comments instead of interpret all the code without that information.

**Comment by anywhichway** [comment]
Ok ... will add more comments.
