### ISSUE TITLE
loops and reactive data model?

### ISSUE THREAD

**Issue by pwFoo** [anywhichway/tlx#9]
Would be great to loop through objects and use the key inside of the loop?
```
    <table id="forvalues" t-forvalues="${persons}">
        <tr>
            <td>Name: ${name}</td><td>Alter: ${age}</td>
        </tr>
    </table>
```

And remove / append / update the array of objects with javascript / web developer console
But looks like loops don't work reactive?
From examples
```
<table id="foreach" t-foreach="${items}">
<tr>
<td>${index}</td><td>${value}</td>
</tr>
</table>
```
```
const items = tlx.reactor([1,2,3])
tlx.view(document.getElementById("foreach"),{model:items});
```

**Comment by anywhichway** [comment]
@pwFoo With respect to looping through and using keys on objects this would increase the chance of variable name collisions and overwrites that would be hard to debug, suggest you just use `${value.name}` and `${value.age}` for your example above.  For example to support resolving based on just the key, if you had an object with the key `value`, you could still use `${value.value}`, if your request was implemented the `value` property would shadow the object.

With respect to reactive loops, try the below:

```
<html lang="en">
<head>
<script src="https://unpkg.com/tlx/browser/tlx.min.js"></script>
<script src="../index.js"></script>
</head>
<body>
<div>
In the debugger console type "items[0]=3" and the content should update.</div>
<table id="foreach" t-foreach="${items}">
<tr>
<td>${index}</td><td>${value}</td>
</tr>
</table>
<script>
const items = tlx.reactor([1,2,3])
tlx.view(document.getElementById("foreach"),{model:items});
</script>
</body>
</html>
```

**Comment by pwFoo** [comment]
Hi @anywhichway 
change existing lines works fine.
Problem is append / prepend data (rows). With some more testing it looks like a append bug? Prepend works fine and triggers the appended data too.

Example
```
const items = tlx.reactor(["one", "two", "three"])
```

Result
```
0	one
1	two
2	three
```

Now I try to append data
```
items.push("four")
items.push("five", "six")
```

Result (unchanged!!!)
```
0	one
1	two
2	three
```
Expected: Add the lines in view.

Now I try to prepend data
```
items.unshift("zero")
```

Result
```
0	zero
1	one
2	two
3	three
4	four
5	five
6	six
```
Prepend works AND has triggered the missing appended data...?!

**Comment by pwFoo** [comment]
prepend / append an array of data could be a bug too (or I do it wrong with JS?).
```
var test = ["zero1", "zero2"]
items.unshift(test)
```

Result
```

0 zero1,zero2
1 one
2 two
3 three
```

Expected
```
0 zero1
1 zero2
2 one
3 two
4 three
```

**Comment by anywhichway** [comment]
Aha ... this is a fairly typical issue when proxying arrays and using push,
splice, etc. I know how to fix; however it will probably add several
hundred bytes so give me day or son to address. I want to keep the size
down.

**Comment by pwFoo** [comment]
@anywhichway 
Ok, take the time you need. 👍

**Comment by anywhichway** [comment]
@pwFoo Nothing like fresh eyes. I have dealt with the array Proxy issue multiple times in the past and always solved it a similar way. Came up with an entirely new way to address and it took less than 100 bytes compressed. See updated examples/issue9.html.

**Comment by pwFoo** [comment]
Works fine now 👍
